//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by W3ZMapEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_TILEPOINTS                  104
#define ID_VIEW_VIEW1                   104
#define ID_VIEW_VIEW2                   105
#define ID_PLUGIN_TIMER                 106
#define IDR_MAINFRAME                   128
#define IDD_BAR_EDITMODE                128
#define IDR_W3ZMAPTYPE                  129
#define IDR_TOOLBARS                    131
#define IDD_BAR_TILE                    133
#define IDD_BAR_DOODADS                 134
#define IDD_BAR_UNITS                   135
#define IDR_SHADOWSBAR                  136
#define IDD_PAGE_MAPPROP                140
#define IDC_DOODADS                     143
#define IDC_SHADOWS                     144
#define IDC_PATH                        145
#define IDC_UNITS                       146
#define IDR_TILESBAR                    149
#define IDC_PEN                         151
#define IDD_BAR_VIEWMODE                152
#define IDD_PAGE_PLAYERSPROP            153
#define IDR_DOODADSBAR                  154
#define IDR_ZOOMBAR                     156
#define IDD_DLG_DOODADTOOL_PROP         160
#define IDD_DLG_TILEPOINTTOOL_PROP      161
#define IDC_TILEPOINTS_SEL              163
#define IDC_TILEPOINTS_REPLACE          164
#define IDR_POPUPS                      167
#define IDD_DLG_OPTIONS                 171
#define IDC_TILEPOINTS_FILL             172
#define IDD_PAGE_MAPSIZE                173
#define IDD_PAGE_MAPPROTECT             174
#define IDD_DLG_PROTECT_PASS            175
#define IDD_PAGE_MAPMENUOPT             176
#define IDD_DLG_STATISTICS              177
#define IDD_BAR_PATHING                 179
#define IDD_DLG_PROGRESS                182
#define IDD_PAGE_MINIMAP                184
#define IDD_DLG_NEWMAP                  186
#define IDD_DLG_SCM_CONVOPT             187
#define IDD_DLG_PLUGIN_RUN              188
#define IDD_DLG_RUN_PLUGIN              189
#define IDC_EDITMODE                    1004
#define IDC_EDT_UNIT_Y                  1007
#define IDC_EDT_TILE_HEIGHT             1008
#define IDC_CHK_TILE_WATER              1009
#define IDC_EDT_DOO_LIFE                1010
#define IDC_EDT_TILE_WATER_LEVEL        1010
#define IDC_EDT_DOO_SC_X                1011
#define IDC_CHK_TILE_SHADOW             1011
#define IDC_EDT_DOO_SC_Y                1012
#define IDC_CMB_UNIT_OWNER              1012
#define IDC_EDT_MAPDESC                 1013
#define IDC_EDT_DOO_SC_Z                1013
#define IDC_EDT_UNIT_X                  1014
#define IDC_SPN_DETAILS                 1015
#define IDC_SPN_LAYER                   1016
#define IDC_SPN_HEIGHT                  1017
#define IDC_SPN_WATER_LEVEL             1018
#define IDC_EDT_MAPPLAYREC              1019
#define IDC_EDT_MAPNBPLAYERS            1020
#define IDC_EDT_MAPWIDTH                1021
#define IDC_EDT_MAPHEIGHT               1022
#define IDC_CMB_MAPTYPE                 1023
#define IDC_EDT_MAPGROUND               1024
#define IDC_EDT_MAPCLIFF                1025
#define IDC_EDT_MAPNAME                 1026
#define IDC_EDT_MAPAUTHOR               1027
#define IDC_EDT_DOO_X                   1029
#define IDC_EDT_DOO_Y                   1030
#define IDC_CMB_TILE_GROUND             1032
#define IDC_EDT_DOO_Z                   1032
#define IDC_CMB_TILE_CLIFF              1034
#define IDC_EDT_TILE_DETAILS            1035
#define IDC_EDT_TILE_LAYER              1036
#define IDC_SCRINFOS                    1037
#define IDC_STATICQUAD                  1038
#define IDC_STATICZEP                   1039
#define IDC_EDTFLAGS                    1041
#define IDC_CHK_TILE_MINIMAPSHD         1066
#define IDC_CHK_TILE_RAMP               1067
#define IDC_CHK_TILE_BLIGHT             1068
#define IDC_EDT_DOO_FLAGS               1069
#define IDC_CHK_DOODADS                 1070
#define IDC_RAD_TILES                   1071
#define IDC_RAD_LEVEL                   1072
#define IDC_CHK_UNITS                   1073
#define IDC_CHK_SHADOWS                 1074
#define IDC_CHK_PATH                    1075
#define IDC_CHK_PLAYERS                 1076
#define IDC_EDT_PLAY_WIDTH              1077
#define IDC_CHK_TILES_BOUNDARIES        1077
#define IDC_EDT_PLAY_HEIGHT             1078
#define IDC_CHK_TILES_WEBOUNDS          1078
#define IDC_EDT_TOP_LEFT_X              1079
#define IDC_CHK_TILES_WATER             1079
#define IDC_EDT_TOP_LEFT_Y              1080
#define IDC_CHK_TILES_RAMPS             1080
#define IDC_EDT_TOP_RIGHT_X             1081
#define IDC_CHK_TILES_BLIGHTS           1081
#define IDC_EDT_TOP_RIGHT_Y             1082
#define IDC_CHK_TILES_LAYERS            1082
#define IDC_EDT_BOTTOM_LEFT_X           1083
#define IDC_EDT_BOTTOM_LEFT_Y           1084
#define IDC_EDT_BOTTOM_RIGHT_X          1085
#define IDC_EDT_BOTTOM_RIGHT_Y          1086
#define IDC_CHK_PLAYER01                1087
#define IDC_EDT_PLAY_WIDTH2             1087
#define IDC_CHK_PLAYER02                1088
#define IDC_EDT_PLAY_HEIGHT2            1088
#define IDC_CHK_PLAYER04                1089
#define IDC_EDT_PLAY_WIDTH3             1089
#define IDC_CHK_PLAYER05                1090
#define IDC_EDT_PLAY_HEIGHT3            1090
#define IDC_CHK_PLAYER06                1091
#define IDC_CHK_PLAYER07                1092
#define IDC_CHK_PLAYER08                1093
#define IDC_CHK_PLAYER09                1094
#define IDC_CHK_PLAYER10                1095
#define IDC_CHK_PLAYER11                1096
#define IDC_CHK_PLAYER12                1097
#define IDC_EDT_X_01                    1098
#define IDC_EDT_Y_01                    1099
#define IDC_EDT_NAME_01                 1100
#define IDC_CMB_FORCE01                 1101
#define IDC_EDT_DOO_TYPE                1103
#define IDC_CMB_DOO_VARIATION           1106
#define IDC_EDT_DOO_ANGLE               1107
#define IDC_EDT_DOO_ID                  1108
#define IDC_EDT_GROUND_LEVEL            1109
#define IDC_EDT_WATER_LEVEL             1110
#define IDC_CHK_DOO_NON_SOLID           1114
#define IDC_CHK_DOO_NORMAL              1115
#define IDC_EDT_UNIT_TYPE               1116
#define IDC_BTN_UNIT_ADD_PROP           1117
#define IDC_EDT_MAP_VER                 1118
#define IDC_EDT_EDITOR_VER              1119
#define IDC_CHK_GROUND_TYPE             1129
#define IDC_CHK_CLIFF_TYPE              1130
#define IDC_CHK_DETAILS                 1131
#define IDC_CHK_LAYER                   1132
#define IDC_CHK_TILEPOINT_HEIGHT        1133
#define IDC_CHK_WATER_LEVEL             1134
#define IDC_CHK_DOODAD_TYPE             1136
#define IDC_CHK_DOODAD_VARIATION        1137
#define IDC_BTN_GROUND_TILESETS         1137
#define IDC_BTN_PATH_NOFLY              1137
#define IDC_CANCEL                      1137
#define IDC_CHK_DOODAD_ANGLE            1138
#define IDC_BTN_PATH_NOWALK             1138
#define IDC_BTN_REGISTER                1138
#define IDC_EDT_DETAILS_RANGE           1139
#define IDC_BTN_PATH_BLIGHT             1139
#define IDC_CHK_DOODAD_SCALE_X          1140
#define IDC_BTN_PATH_UNKNOWN            1140
#define IDC_CHK_DOODAD_SCALE_Y          1141
#define IDC_EDT_GRND_HEIGHT_AMP         1141
#define IDC_BTN_PATH_UNKN01             1141
#define IDC_CHK_DOODAD_SCALE_Z          1142
#define IDC_EDT_WATER_HEIGHT_AMP        1142
#define IDC_BTN_PATH_UNKN02             1142
#define IDC_CHK_DOODAD_LIFE             1143
#define IDC_EDT_TILEPOINT_PEN_SIZE      1143
#define IDC_CHK_AUTO_SAVE               1144
#define IDC_CHK_CUSTOM_TILESETS         1144
#define IDC_CHK_ENABLE_PROTECT          1144
#define IDC_EDT_PATH_PEN_SIZE           1145
#define IDC_EDT_DOODADS_TYPE_LIST       1146
#define IDC_EDT_DOODADS_VARIATION       1147
#define IDC_EDT_UNDO_LVL                1147
#define IDC_EDT_DOODADS_SPACING         1148
#define IDC_EDT_TEMP_DIR                1148
#define IDC_EDT_DOODADS_ANGLE           1149
#define IDC_EDT_DOODADS_MINSCALE_X      1150
#define IDC_EDT_DOODADS_MINSCALE_Y      1151
#define IDC_EDT_AUTOSAVE_TIME           1151
#define IDC_EDT_DOODADS_MINSCALE_Z      1152
#define IDC_EDT_BOUND_FACTOR            1152
#define IDC_EDT_DOODADS_MAXSCALE_X      1153
#define IDC_EDT_LEVEL_FACTOR            1153
#define IDC_EDT_DOODADS_MAXSCALE_Y      1154
#define IDC_EDT_DOODADS_MAXSCALE_Z      1155
#define IDC_EDT_DOODADS_MIN_LIFE        1156
#define IDC_EDT_PASSWORD                1156
#define IDC_EDT_DOODADS_MAX_LIFE        1157
#define IDC_RAD_RESCALE                 1157
#define IDC_EDT_DOODADS_PEN_SIZE        1158
#define IDC_RAD_CUTOUT                  1158
#define IDC_EDT_CUTOFS_X                1159
#define IDC_EDT_CUTOFS_Y                1160
#define IDC_CMB_PROTECTTYPE             1162
#define IDC_EDT_PROTECTAPASS            1163
#define IDC_EDT_PROTECTPPASS            1164
#define IDC_CHK_PROTECTUNPREC           1165
#define IDC_CHK_PROTECTBACKUP           1166
#define IDC_CHK_PROTECTAUTHORMSG        1167
#define IDC_EDT_STATISTICS              1168
#define IDC_EDT_PROTECTVER              1169
#define IDC_RAD_PROTECTLVL1             1170
#define IDC_RAD_PROTECTLVL2             1171
#define IDC_STC_PROTECTSTATUS           1172
#define IDC_BTN_CLIFF_TILESETS          1173
#define IDC_RAD_PROTECTLVL3             1173
#define IDC_STA_PATH_NOWALK             1176
#define IDC_BTN_PATH_NOBUILD            1177
#define IDC_STA_PATH_NOBUILD            1178
#define IDC_STC_PATH_NOFLY              1179
#define IDC_BTN_PATH_NOWATER            1180
#define IDC_STC_PATH_BLIGHT             1181
#define IDC_STA_PATH_NOWATER            1182
#define IDC_STC_PATH_UNKNOWN            1183
#define IDC_STC_PATH_UNKN01             1184
#define IDC_BTN_PATH_RESET              1185
#define IDC_STC_PATH_CURRENT            1186
#define IDC_EDT_ORG_AUTHOR_NAME         1187
#define IDC_STC_PATH_UNKN02             1187
#define IDC_PRGS_PROGRESSBAR            1188
#define IDC_STA_PROGRESSMSG             1190
#define IDC_STA_REGISTERED              1192
#define IDC_BTN_MINIMAP_RESET           1193
#define IDC_CMB_MINIMAP_ICONS           1195
#define IDC_STA_MINIMAP_ICONCOLOR       1197
#define IDC_BTN_MINIMAP_REMOVEALL       1198
#define IDC_RAD_MINIMAP_ADD             1199
#define IDC_RAD_MINIMAP_SELECT          1200
#define IDC_RAD_MINIMAP_REMOVE          1201
#define IDC_BTN_MINIMAP_COLORS          1202
#define IDC_CHECK1                      1204
#define IDC_CHECK2                      1205
#define IDC_CHECK3                      1206
#define IDC_BTN_IMPORTPREVIEW           1207
#define IDC_CHK_HIDEMINIMAP             1209
#define IDC_BTN_UPDATEPIC               1210
#define IDC_CHK_INCLUDEPREVIEW          1211
#define IDC_BTN_IMPORTMINIMAP           1212
#define IDC_BTN_EXPORTMINIMAP           1213
#define IDC_BTN_COMPUTECAMBNDS          1214
#define IDC_BUTTON2                     1215
#define IDC_CHK_WAVESCLIFF              1216
#define IDC_CHK_WAVESROLLING            1217
#define IDC_CHK_PARTIALVIS              1218
#define IDC_CHK_MELEE                   1219
#define IDC_CHK_FL_UNKNOWN1             1220
#define IDC_CHK_FL_UNKNOWN0             1221
#define IDC_RAD_SCM_SAMEDIM             1222
#define IDC_RAD_SCM_EVEN                1224
#define IDC_RAD_SCM_ANGLES              1225
#define IDC_CHK_SCM_45DEG               1226
#define IDC_CHK_SCM_BOUNDS              1227
#define IDC_CHK_SCM_SMOOTH              1228
#define IDC_EDT_PLUG_PLUGNAME           1229
#define IDC_EDT_PLUG_FILENAME           1230
#define IDC_CMB_PLUGIN_LIST             1233
#define IDC_COMBO1                      1234
#define ID_TILESEDIT                    32771
#define ID_DOODADSEDIT                  32772
#define ID_PATHEDIT                     32773
#define ID_SHADOWSEDIT                  32774
#define ID_UNITSEDIT                    32775
#define ID_BTN_SHAD_PEN                 32778
#define ID_BTN_SHAD_FILL                32779
#define ID_BTN_PATH_NOB_NOW_FOK         32782
#define ID_BTN_PATH_NOB_WOK_FOK         32785
#define ID_BTN_PATH_BOK_WOK_NOF         32786
#define ID_BTN_PATH_NOB_WOK_NOF         32787
#define ID_BTN_PATH_BOK_NOW_NOF         32788
#define ID_VIEW_EDITMODEBAR             32789
#define ID_EDIT_MAP_PROPERTIES          32790
#define ID_VIEW_EDITTOOLBARSBAR         32791
#define ID_VIEW_REFRESH                 32795
#define ID_BTN_SHAD_ERASE               32801
#define ID_FILE_IMPORT                  32813
#define ID_VIEW_STATISTICS              32814
#define ID_VIEW_VIEWMODEBAR             32815
#define ID_BTN_DOOD_ADD                 32816
#define ID_BTN_DOOD_DELETE              32817
#define ID_BTN_DOOD_REPLACE             32818
#define ID_BTN_DOOD_SELECT              32819
#define ID_BTN_DOOD_RECT_FILL           32820
#define ID_BTN_DOOD_ELLIPSE_FILL        32821
#define ID_BTN_DOOD_UPDT                32822
#define ID_BTN_TILE_SELECT              32823
#define ID_BTN_TILE_PEN                 32824
#define ID_BTN_TILE_RECT                32825
#define ID_BTN_TILE_ELLIPSE             32826
#define ID_BTN_TILE_FILL                32827
#define ID_BTN_TILE_REPLACE             32828
#define ID_BTN_TILE_RAND                32829
#define ID_BTN_TILE_SLOPE               32830
#define ID_BTN_TILE_BENDUP              32831
#define ID_BTN_TILE_BENDDOWN            32832
#define ID_BTN_TILE_FLAT                32833
#define ID_BTN_DOOD_RECT                32834
#define ID_BTN_DOOD_ELLIPSE             32835
#define ID_BTN_SHAD_SQUARE              32836
#define ID_BTN_SHAD_ELIPSE              32837
#define ID_BTN_ZOOM_IN                  32838
#define ID_BTN_ZOOM_OUT                 32839
#define ID_BTN_ZOOM_NO                  32840
#define ID_BTN_TILE_RAND_WATER          32846
#define ID_BTN_TILE_SLOPE_WATER         32847
#define ID_BTN_TILE_BENDUP_WATER        32848
#define ID_BTN_TILE_BENDDOWN_WATER      32849
#define ID_BTN_TILE_FLAT_WATER          32850
#define ID_VIEW_ZOOMBAR                 32851
#define ID_BTN_PATH_BOK_NOW_FOK         32852
#define ID_BTN_PATH_NOB_NOW_NOF         32855
#define ID_BTN_PATH_BOK_WOK_FOK         32856
#define ID_BTN_TILE_ROTATE              32857
#define ID_BTN_TILE_H_MIRROR            32858
#define ID_BTN_TILE_V_MIRROR            32859
#define ID_POPTPB_PROPERTIES            32862
#define ID_POPTPB_HELP                  32863
#define ID_POPDB_PROPERTIES             32867
#define ID_POPDB_HELP                   32868
#define ID_POPPB_PROPERTIES             32870
#define ID_POPPB_HELP                   32871
#define ID_BTN_PATH_RESET               32873
#define ID_BTN_DOOD_SPACING             32874
#define ID_HELP_HOWTO                   32880
#define ID_BTN_DOOD_MOVE                32882
#define ID_FILE_EXPORT                  32883
#define ID_FILE_EXPORT_GROUNDMAP        32884
#define ID_FILE_EXPORT_STATISTICS       32885
#define ID_FILE_EXPORT_MINIMAP          32886
#define ID_FILE_IMPORT_GROUNDMAP        32887
#define ID_FILE_IMPORT_PATHMAP          32888
#define ID_FILE_EXPORT_PATHMAP          32889
#define ID_FILE_IMPORT_MINIMAP          32890
#define ID_EDIT_MAP_PROTECTION          32892
#define ID_FILE_IMPORT_PREVIEWIMAGE     32894
#define ID_FILE_EXPORT_PREVIEWIMAGE     32895
#define ID_FILE_IMPORT_CUSTOMTILESET    32896
#define ID_VIEW_3DVIEW                  32897
#define ID_FILE_IMPORT_SLKFILE          32898
#define ID_EDIT_MAP_RESIZEMAP           32899
#define ID_FILE_QUICKBACKUP             32900
#define ID_FILE_IMPORT_JASSSCRIPT       32901
#define ID_FILE_EXPORT_JASSSCRIPT       32902
#define ID_OPTIONS_SAVESETTINGS         32904
#define ID_OPTIONS_PREFERENCES          32905
#define ID_EDIT_MAP_MENUOPTIONS         32906
#define ID_EDIT_PLAYERSPROPERTIES       32907
#define ID_EDIT_MINIMAP                 32908
#define ID_PLUGINS                      32909
#define IDS_VIEW_POSITION               61216
#define IDS_TESTSTRING                  61217

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32910
#define _APS_NEXT_CONTROL_VALUE         1235
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
